# config.yaml
experiment:
  num_trials: 10
  num_epochs: 5
  final_epochs: 10

model:
  type: resnet50    # Options: resnet50, simplenn
  lr: 0.0001
  weight_decay: 0.001

dataset:
  path: "~/tmp/Dataset/Wafermap-dataset/WM811K.pkl"
